import{useEffect,useState}from"react";import{api}from"./api";
export default function App(){const[me,setMe]=useState<any>(null),[seasons,setSeasons]=useState<any[]>([]),[players,setPlayers]=useState<any[]>([]),[name,setName]=useState(""),[matches,setMatches]=useState<any[]>([]),[sid,setSid]=useState<number|null>(null),[err,setErr]=useState("");
useEffect(()=>{if(localStorage.getItem("token")){api("/api/me").then(setMe).catch(()=>{});load()}},[]);
async function load(){setSeasons(await api("/api/seasons"));setPlayers(await api("/api/players"))}
async function create(){if(!name)return;await api("/api/seasons",{method:"POST",body:JSON.stringify({name})});setName("");load()}
async function select(id:number){setSid(id);setMatches(await api(`/api/seasons/${id}/matches`))}
async function gen(){await api(`/api/seasons/${sid}/generate`,{method:"POST"});await select(sid!)}
async function score(id:number){const h=prompt("Uy egasi goli?");const a=prompt("Mehmon goli?");if(h===null||a===null)return;await api(`/api/matches/${id}/score`,{method:"POST",body:JSON.stringify({home_score:Number(h),away_score:Number(a)})});await select(sid!)}
async function ban(id:number,banned:boolean){await api(`/api/admin/players/${id}/status`,{method:"POST",body:JSON.stringify({status:banned?"ACTIVE":"BANNED"})});load()}
async function login(){const u=prompt("Admin username","admin");const p=prompt("Admin password","admin123");if(!u||!p)return;try{const x=await api("/api/auth/login",{method:"POST",body:JSON.stringify({username:u,password:p})});localStorage.setItem("token",x.token);setMe(x.user);load()}catch(e:any){setErr(e.message)}}
return <main><header><h1>👑 eFootball Admin</h1>{me?<b>{me.username}</b>:<button onClick={login}>Kirish</button>}</header>{err&&<p className="error">{err}</p>}{me?.role==="ADMIN"&&<><div className="new"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Liga nomi"/><button onClick={create}>Liga yaratish</button></div><h2>Ligalar</h2>{seasons.map(s=><div className="row" key={s.id}><span><b>{s.name}</b> — {s.status}</span><button onClick={()=>select(s.id)}>O‘yinlar</button></div>)}{sid&&<><button onClick={gen}>⚙️ Avtomatik fixture</button>{matches.map(m=><div className="match" key={m.id}>Tur {m.round_number}: {m.home} vs {m.away} — {m.played?`${m.home_score}:${m.away_score}`:"-"} <button onClick={()=>score(m.id)}>Natija</button></div>)}</>}<h2>Foydalanuvchilar</h2>{players.map(p=><div className="row" key={p.id}><span>{p.first_name||p.username} {p.telegram_username?`(@${p.telegram_username})`:""} {p.telegram_id?`[TG:${p.telegram_id}]`:""}</span><button onClick={()=>ban(p.id,p.is_banned)}>{p.is_banned?"Unban":"Ban"}</button></div>)}</>}</main>}